module.exports = {
  EDITOR_EDIT_SCRIPT: 'EDITOR_EDIT_SCRIPT',

  // player

  EDITOR_START_PLAYER: 'EDITOR_START_PLAYER',
  EDITOR_STOP_PLAYER: 'EDITOR_STOP_PLAYER',

  // vr

  EDITOR_ENTER_VR: 'EDITOR_ENTER_VR',
  EDITOR_ENTERED_VR: 'EDITOR_ENTERED_VR',
  EDITOR_EXITED_VR: 'EDITOR_EXITED_VR',
  EDITOR_FAILED_VR: 'EDITOR_FAILED_VR',

  // actions

  EDITOR_SHOW_MODAL: 'EDITOR_SHOW_MODAL',

  // notifications

  EDITOR_CLEARED: 'EDITOR_CLEARED',

  EDITOR_SAVING_STARTED: 'EDITOR_SAVING_STARTED',
  EDITOR_SAVING_FINISHED: 'EDITOR_SAVING_FINISHED',

  EDITOR_THEME_CHANGED: 'EDITOR_THEME_CHANGED',

  EDITOR_TRANSFORM_MODE_CHANGED: 'EDITOR_TRANSFORM_MODE_CHANGED',
  EDITOR_TRANSFORM_SNAP_CHANGED: 'EDITOR_TRANSFORM_SNAP_CHANGED',
  EDITOR_TRANSFORM_SPACE_CHANGED: 'EDITOR_TRANSFORM_SPACE_CHANGED',
  EDITOR_RENDERER_CHANGED: 'EDITOR_RENDERER_CHANGED',

  EDITOR_SCENE_BACKGROUND_CHANGED: 'EDITOR_SCENE_BACKGROUND_CHANGED',
  EDITOR_SCENE_FOG_CHANGED: 'EDITOR_SCENE_FOG_CHANGED',
  EDITOR_SCENE_GRAPH_CHANGED: 'EDITOR_SCENE_GRAPH_CHANGED',

  EDITOR_CAMERA_CHANGED: 'EDITOR_CAMERA_CHANGED',

  EDITOR_GEOMETRY_CHANGED: 'EDITOR_GEOMETRY_CHANGED',

  EDITOR_OBJECT_SELECTED: 'EDITOR_OBJECT_SELECTED',
  EDITOR_OBJECT_FOCUSED: 'EDITOR_OBJECT_FOCUSED',

  EDITOR_OBJECT_ADDED: 'EDITOR_OBJECT_ADDED',
  EDITOR_OBJECT_CHANGED: 'EDITOR_OBJECT_CHANGED',
  EDITOR_OBJECT_REMOVED: 'EDITOR_OBJECT_REMOVED',

  EDITOR_HELPER_ADDED: 'EDITOR_HELPER_ADDED',
  EDITOR_HELPER_REMOVED: 'EDITOR_HELPER_REMOVED',

  EDITOR_MATERIAL_CHANGED: 'EDITOR_MATERIAL_CHANGED',

  EDITOR_SCRIPT_ADDED: 'EDITOR_SCRIPT_ADDED',
  EDITOR_SCRIPT_CHANGED: 'EDITOR_SCRIPT_CHANGED',
  EDITOR_SCRIPT_REMOVED: 'EDITOR_SCRIPT_REMOVED',

  EDITOR_WINDOW_RESIZE: 'EDITOR_WINDOW_RESIZE',

  EDITOR_SHOW_GRID_CHANGED: 'EDITOR_SHOW_GRID_CHANGED',
  EDITOR_REFRESH_SIDEBAR_OBJECT_3D: 'EDITOR_REFRESH_SIDEBAR_OBJECT_3D',
  EDITOR_HISTORY_CHANGED: 'EDITOR_HISTORY_CHANGED',
  EDITOR_REFRESH_SCRIPT_EDITOR: 'EDITOR_REFRESH_SCRIPT_EDITOR',

  AUTH_LOAD_INFO: 'AUTH_LOAD_INFO',
  AUTH_LOAD_INFO_SUCCESS: 'AUTH_LOAD_INFO_SUCCESS',
  AUTH_LOAD_INFO_FAIL: 'AUTH_LOAD_INFO_FAIL',
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAIL: 'AUTH_LOGIN_FAIL',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS',
  AUTH_LOGOUT_FAIL: 'AUTH_LOGOUT_FAIL',
  AUTH_LOAD_AUTH: 'AUTH_LOAD_AUTH',
  AUTH_LOAD_AUTH_SUCCESS: 'AUTH_LOAD_AUTH_SUCCESS',
  AUTH_LOAD_AUTH_NULL: 'AUTH_LOAD_AUTH_NULL',
  AUTH_LOAD_AUTH_FAIL: 'AUTH_LOAD_AUTH_FAIL',
};
